# Horizontal Pod AutoScaler (HPA)
# To produce some load on the service we will use, a tool called wrk. The following will open 600 connections using 600 threads for a period of 15 min
# docker run --rm loadimpact/loadgentest-wrk -c 600 -t 600 -d 15m <http://URL/IP>
# Make 100 requests to a http/s target URL/IP:
# for i in $(seq 1 100); do curl -s -o /dev/null "<http://URL/IP>"; done
# To get HPA details: kubectl get hpa


apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: hello-world-hpa

spec:
 scaleTargetRef:
   apiVersion: apps/v1beta1
   kind: Deployment
   name: hello-world-app
 minReplicas: 1
 maxReplicas: 1
 targetCPUUtilizationPercentage: 60